server.port=8761
spring.application.name=eureka-server

# VERY IMPORTANT FIX
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# ADD THIS ALSO (fix infinite retry issue)
eureka.server.enable-self-preservation=false